DEBUG = True
SQLALCHEMY_DATABASE_URI = 'mysql://descartes_gama:lpinfo@mysql-descartes.alwaysdata.net/descartes_mexique'
SECRET_KEY = 'mysecret'
STATIC = 'static'
MAIL_SERVER='smtp-descartes.alwaysdata.net'
MAIL_USERNAME='descartes@alwaysdata.net'
MAIL_PASSWORD='lpinfo'
MAIL_PORT=465
MAIL_USE_SSL=True
MAIL_USE_TLS = False